# Generated by Django 5.2.15 on 2026-06-28 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=32)),
                ('custom_api_calls_monthly', models.IntegerField(blank=True, null=True)),
                ('custom_storage_bytes', models.BigIntegerField(blank=True, null=True)),
                ('custom_function_invocations', models.IntegerField(blank=True, null=True)),
                ('custom_ai_tokens', models.IntegerField(blank=True, null=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=128)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=128)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.project')),
            ],
        ),
        migrations.CreateModel(
            name='QuotaUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('api_calls', models.BigIntegerField(default=0)),
                ('function_invocations', models.BigIntegerField(default=0)),
                ('ai_tokens', models.BigIntegerField(default=0)),
                ('storage_bytes', models.BigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_usages', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'year', 'month')},
            },
        ),
    ]
