# Generated by Django 5.2.15 on 2026-06-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_created_by_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_owner_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_project_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_created_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated_by',
        ),
        migrations.RenameIndex(
            model_name='project',
            new_name='core_projec_owner_i_f31741_idx',
            old_name='core_project_owner_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='projectmembership',
            new_name='core_projec_project_2a87ef_idx',
            old_name='core_project_project_role_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtokenblacklist',
            new_name='core_refres_jti_5d3d18_idx',
            old_name='core_refresh_jti_idx',
        ),
        migrations.RenameIndex(
            model_name='refreshtokenblacklist',
            new_name='core_refres_user_id_e56abf_idx',
            old_name='core_refresh_user_created_idx',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
