# Generated by Django 5.2.15 on 2026-06-28 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_id', models.CharField(blank=True, help_text='Client-generated anon ID', max_length=256)),
                ('event_name', models.CharField(db_index=True, max_length=256)),
                ('properties', models.JSONField(default=dict)),
                ('session_id', models.CharField(blank=True, max_length=256)),
                ('platform', models.CharField(blank=True, help_text='web|ios|android|server', max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='core.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'event_name', 'timestamp'], name='analytics_a_project_dfa33d_idx'), models.Index(fields=['project', 'user', 'timestamp'], name='analytics_a_project_c5cc0e_idx'), models.Index(fields=['project', 'timestamp'], name='analytics_a_project_f88c6b_idx')],
            },
        ),
    ]
