# Generated by Django 5.2.15 on 2026-06-28 11:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], db_index=True, default='draft', max_length=16)),
                ('targeting_key', models.CharField(default='user_id', help_text='Field used for deterministic assignment: user_id, session_id, device_id', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abtesting_experiments', to='core.project')),
            ],
            options={
                'db_table': 'abtesting_experiment',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. "control", "variant_a"', max_length=64)),
                ('description', models.TextField(blank=True)),
                ('allocation', models.IntegerField(default=50, help_text='Percentage 0-100; all variants in an experiment must sum to 100')),
                ('config', models.JSONField(default=dict, help_text='Variant-specific config values exposed to the client')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='abtesting.experiment')),
            ],
            options={
                'db_table': 'abtesting_experiment_variant',
                'ordering': ['name'],
                'unique_together': {('experiment', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExperimentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('targeting_value', models.CharField(help_text='The actual user_id / session_id / device_id value', max_length=256)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='abtesting.experiment')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='abtesting.experimentvariant')),
            ],
            options={
                'db_table': 'abtesting_experiment_assignment',
            },
        ),
        migrations.CreateModel(
            name='ExperimentConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=128)),
                ('value', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='abtesting.experimentassignment')),
            ],
            options={
                'db_table': 'abtesting_experiment_conversion',
                'indexes': [models.Index(fields=['assignment', 'event_name'], name='abtesting_e_assignm_47e704_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='experimentassignment',
            index=models.Index(fields=['experiment', 'variant'], name='abtesting_e_experim_bf7cfe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentassignment',
            unique_together={('experiment', 'targeting_value')},
        ),
    ]
