apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ownfirebase.fullname" . }}-celery-worker
  labels:
    {{- include "ownfirebase.componentLabels" (dict "context" . "component" "celery-worker") | nindent 4 }}
spec:
  replicas: {{ .Values.celeryWorker.replicaCount }}
  selector:
    matchLabels:
      {{- include "ownfirebase.componentSelectorLabels" (dict "context" . "component" "celery-worker") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ownfirebase.componentSelectorLabels" (dict "context" . "component" "celery-worker") | nindent 8 }}
      {{- with .Values.celeryWorker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "ownfirebase.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "ownfirebase.waitForDeps" . | nindent 8 }}
      containers:
        - name: celery-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - celery
            - -A
            - ownfirebase
            - worker
            - -l
            - info
          {{- include "ownfirebase.envFrom" . | nindent 10 }}
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - celery -A ownfirebase inspect ping -d "celery@$HOSTNAME" -t 10
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 15
            failureThreshold: 3
          resources:
            {{- toYaml .Values.celeryWorker.resources | nindent 12 }}
      {{- with .Values.celeryWorker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celeryWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
