{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ownfirebase.fullname" . }}-postgres
  labels:
    {{- include "ownfirebase.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.persistence.storageClassName }}
  storageClassName: {{ .Values.postgresql.persistence.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size }}
{{- end }}
