{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ownfirebase.fullname" . }}-postgres
  labels:
    {{- include "ownfirebase.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "ownfirebase.componentSelectorLabels" (dict "context" . "component" "postgres") | nindent 4 }}
{{- end }}
