# Generated by Django 5.2.15 on 2026-06-28 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('embedding_model', models.CharField(default='text-embedding-3-small', max_length=64)),
                ('dimensions', models.IntegerField(default=1536)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vector_collections', to='core.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VectorDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, help_text='Optional caller-provided ID', max_length=255)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('embedding', models.JSONField(blank=True, help_text='List of floats — embedding vector', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag.vectorcollection')),
            ],
            options={
                'indexes': [models.Index(fields=['collection', 'external_id'], name='rag_vectord_collect_ca76df_idx')],
            },
        ),
    ]
