# Generated by Django 5.2.15 on 2026-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enhanced_auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customtoken',
            new_name='enhanced_au_project_0fc4e9_idx',
            old_name='eauth_customtoken_project_uid_idx',
        ),
        migrations.RenameIndex(
            model_name='phoneverification',
            new_name='enhanced_au_phone_n_d883b5_idx',
            old_name='eauth_phone_number_status_idx',
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='last_used_counter',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='mfasmscode',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mfasmscode',
            name='code',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='otp_code',
            field=models.CharField(max_length=64),
        ),
    ]
